import React from "react";
import { useSelector, useDispatch } from "react-redux";
import RectDrawer from "./rectDrawer";
import { AppState } from "../../store";
import { MapMode } from "../../store/map/types";
import { setRange, clearRange } from "../../store/map/action";

interface Props { }

const RectControl: React.FC<Props> = props => {
    const { mode } = useSelector((state: AppState) => state.MapReducer);
    const dispatch = useDispatch();
    
    //Handle coordinate rectangle generated by map-gl draw (5 point polygon)
    const onRectangle = (coordinates: number[][]) => {
        const getMin = (arr: number[]) => arr.reduce((acc, curr) => {
            return curr < acc ? curr : acc;
        }, Infinity);

        const getMax = (arr: number[]) => arr.reduce((acc, curr) => {
            return curr > acc ? curr : acc;
        }, -Infinity);

        const lngList = coordinates.map(point => point[0]);
        const latList = coordinates.map(point => point[1]);

        const rect = {
            maxLon: Math.round(getMax(lngList)),
            minLon: Math.round(getMin(lngList)),
            maxLat: Math.round(getMax(latList)),
            minLat: Math.round(getMin(latList))
        };

        dispatch(setRange(rect));
    };

    const clear = () => { dispatch(clearRange()); }

    const drawRect = mode === MapMode.RECT;
    return drawRect ?
        <RectDrawer onRectangle={onRectangle} onClear={clear}/> :
        null;
};

export default RectControl;